<Project>
    <PropertyGroup>
        <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>

        <IsPackable>true</IsPackable>

        <PackageIcon>icon.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseUrl>LICENSE</PackageLicenseUrl>
        <PackageProjectUrl>https://github.com/106-Nauticraft/sas</PackageProjectUrl>
        <Authors>Benoît Maurice</Authors>
    </PropertyGroup>

    <ItemGroup>
        <None Include="../../icon.png" Pack="true" PackagePath="\"/>
        <None Include="../../README.md" Pack="true" PackagePath="\"/>
        <None Include="../../LICENSE" Pack="true" PackagePath="\"/>
    </ItemGroup>
</Project>